from database import SessionLocal, engine
import models

# 1. Recrear la base de datos desde cero
models.Base.metadata.drop_all(bind=engine)
models.Base.metadata.create_all(bind=engine)

def seed_database():
    db = SessionLocal()

    # 2. Crear los Proveedores Reales
    providers_data = ["Sam's", "Walmart", "Carnes Marst", "Central", "Valenciana"]
    providers = {}
    
    for p_name in providers_data:
        provider = models.Provider(name=p_name)
        db.add(provider)
        db.commit()
        db.refresh(provider)
        providers[p_name] = provider

    # 3. Catálogo Maestro Completo de Pizzetas Artesanales
    products_data = [
        # ================= SAM'S =================
        {"name": "Condimento italiano", "unit": "pz", "ideal": 2.0, "provider": "Sam's"},
        {"name": "Albahaca deshidratada", "unit": "pz", "ideal": 2.0, "provider": "Sam's"},
        {"name": "Perejil", "unit": "pzas", "ideal": 3.0, "provider": "Sam's"},
        {"name": "Limón pimienta", "unit": "pz", "ideal": 2.0, "provider": "Sam's"},
        {"name": "Valentina", "unit": "pz", "ideal": 12.0, "provider": "Sam's"},
        {"name": "Maggie", "unit": "pz", "ideal": 16.0, "provider": "Sam's"},
        {"name": "Salsa inglesa", "unit": "pz", "ideal": 24.0, "provider": "Sam's"},
        {"name": "BBQ", "unit": "galón", "ideal": 1.0, "provider": "Sam's"},
        {"name": "Ranch", "unit": "galón", "ideal": 2.0, "provider": "Sam's"},
        {"name": "Buffalo", "unit": "galón", "ideal": 3.0, "provider": "Sam's"},
        {"name": "Pulpa de mago", "unit": "pz", "ideal": 1.0, "provider": "Sam's"},
        {"name": "Fusilli", "unit": "pz", "ideal": 6.0, "provider": "Sam's"},
        {"name": "Fettuchini", "unit": "pz", "ideal": 5.0, "provider": "Sam's"},
        {"name": "Spaghetti", "unit": "paq grd", "ideal": 1.0, "provider": "Sam's"},
        {"name": "Papel de baño", "unit": "pz", "ideal": 1.0, "provider": "Sam's"},
        {"name": "Sanitas", "unit": "pz", "ideal": 16.0, "provider": "Sam's"},
        {"name": "Aderezo miel mostaza", "unit": "galón", "ideal": 1.0, "provider": "Sam's"},
        {"name": "Vinagreta", "unit": "pz", "ideal": 2.0, "provider": "Sam's"},
        {"name": "Crema entera", "unit": "pz", "ideal": 1.0, "provider": "Sam's"},
        {"name": "Crema lincott", "unit": "pz", "ideal": 4.0, "provider": "Sam's"},
        {"name": "Mantequilla", "unit": "barra", "ideal": 0.5, "provider": "Sam's"},
        {"name": "Jabón p/trastes", "unit": "galón", "ideal": 1.0, "provider": "Sam's"},
        {"name": "Lechuga baby", "unit": "pz", "ideal": 1.0, "provider": "Sam's"},
        {"name": "Espinaca baby", "unit": "pz", "ideal": 1.0, "provider": "Sam's"},
        {"name": "Crutones", "unit": "bolsa", "ideal": 1.0, "provider": "Sam's"},
        {"name": "Frijol", "unit": "kilos", "ideal": 6.0, "provider": "Sam's"},
        {"name": "Piña", "unit": "latas chicas", "ideal": 2.0, "provider": "Sam's"},
        {"name": "Aceituna negra", "unit": "bote", "ideal": 1.0, "provider": "Sam's"},
        {"name": "Aceite vegetal", "unit": "pz", "ideal": 1.0, "provider": "Sam's"},
        {"name": "Puré bolognesa", "unit": "latas", "ideal": 3.0, "provider": "Sam's"},
        {"name": "Albacar", "unit": "pz", "ideal": 2.0, "provider": "Sam's"},
        {"name": "Arroz", "unit": "kilo", "ideal": 1.0, "provider": "Sam's"},
        {"name": "Encendedores", "unit": "pz", "ideal": 4.0, "provider": "Sam's"},
        {"name": "Jamón serrano", "unit": "kilo", "ideal": 1.0, "provider": "Sam's"},
        {"name": "Queso de cabra", "unit": "barra", "ideal": 2.0, "provider": "Sam's"},
        {"name": "Panko", "unit": "caja", "ideal": 0.5, "provider": "Sam's"},
        {"name": "Pepinillos", "unit": "bote", "ideal": 1.0, "provider": "Sam's"},
        {"name": "Mayonesa", "unit": "bote", "ideal": 1.0, "provider": "Sam's"},
        {"name": "Empanadas", "unit": "paquetitos", "ideal": 2.0, "provider": "Sam's"},
        {"name": "Tabla de carne", "unit": "pz", "ideal": 2.0, "provider": "Sam's"},
        {"name": "Jitomate deshidratado", "unit": "frasco", "ideal": 1.0, "provider": "Sam's"},
        {"name": "Pan de elote", "unit": "pz", "ideal": 5.0, "provider": "Sam's"},
        {"name": "Valentina", "unit": "galón", "ideal": 1.0, "provider": "Sam's"},
        {"name": "Lechera", "unit": "pz", "ideal": 1.0, "provider": "Sam's"},
        {"name": "Philadelphia para chiles", "unit": "pz", "ideal": 1.0, "provider": "Sam's"},
        {"name": "Salami", "unit": "barra", "ideal": 2.0, "provider": "Sam's"},
        {"name": "Lata de elote", "unit": "pz", "ideal": 1.0, "provider": "Sam's"},
        {"name": "Soya", "unit": "pz", "ideal": 0.5, "provider": "Sam's"},
        {"name": "Ensalada mixtas primavera", "unit": "pz", "ideal": 1.0, "provider": "Sam's"},
        {"name": "Camarones", "unit": "kilos", "ideal": 2.0, "provider": "Sam's"},
        {"name": "Latas de chipotle", "unit": "pz", "ideal": 1.0, "provider": "Sam's"},
        {"name": "Mostaza", "unit": "bote", "ideal": 1.0, "provider": "Sam's"},
        {"name": "Tapete grd para entrada", "unit": "pz", "ideal": 2.0, "provider": "Sam's"},
        {"name": "Tequila José Cuervo", "unit": "botellas", "ideal": 2.0, "provider": "Sam's"},
        {"name": "Bacardi", "unit": "botella", "ideal": 1.0, "provider": "Sam's"},
        {"name": "Buchanan's", "unit": "botellas", "ideal": 2.0, "provider": "Sam's"},
        {"name": "Vodka Sam's Patona", "unit": "patona", "ideal": 1.5, "provider": "Sam's"},
        {"name": "Tequila Sam's", "unit": "botella", "ideal": 1.0, "provider": "Sam's"},
        {"name": "Don simon", "unit": "botellas", "ideal": 9.0, "provider": "Sam's"},
        {"name": "Don simon rosado", "unit": "pz", "ideal": 1.0, "provider": "Sam's"},
        {"name": "Boost", "unit": "pzas", "ideal": 5.0, "provider": "Sam's"},
        {"name": "Caramelo", "unit": "pz", "ideal": 1.0, "provider": "Sam's"},
        {"name": "Agua tónica", "unit": "pzas", "ideal": 9.0, "provider": "Sam's"},
        {"name": "Clamato", "unit": "pzas", "ideal": 3.0, "provider": "Sam's"},
        {"name": "Salsa para cerveza", "unit": "pz", "ideal": 1.0, "provider": "Sam's"},
        {"name": "Jarabe natural", "unit": "galocito", "ideal": 2.0, "provider": "Sam's"},
        {"name": "Granadina", "unit": "botella", "ideal": 2.0, "provider": "Sam's"},
        {"name": "Chamoy", "unit": "botella", "ideal": 0.5, "provider": "Sam's"},
        {"name": "Cerezas", "unit": "bote", "ideal": 0.25, "provider": "Sam's"},
        {"name": "Duraznos", "unit": "latas", "ideal": 1.0, "provider": "Sam's"},
        {"name": "Hershey's", "unit": "galoncito", "ideal": 1.0, "provider": "Sam's"},
        {"name": "Galletas Ore", "unit": "caja chica", "ideal": 1.0, "provider": "Sam's"},
        {"name": "Clavel", "unit": "pzas", "ideal": 2.0, "provider": "Sam's"},
        {"name": "Calahua", "unit": "pz", "ideal": 8.0, "provider": "Sam's"},
        {"name": "Jugo de piña", "unit": "pz", "ideal": 6.0, "provider": "Sam's"},
        {"name": "Philadelphia", "unit": "pz", "ideal": 2.0, "provider": "Sam's"},
        {"name": "Mermelada de fresa", "unit": "pz", "ideal": 1.0, "provider": "Sam's"},
        {"name": "Cajeta", "unit": "frasco", "ideal": 1.0, "provider": "Sam's"},
        {"name": "Crema de avellanas", "unit": "pz", "ideal": 1.0, "provider": "Sam's"},
        {"name": "Crema de cacahuate", "unit": "pz", "ideal": 1.0, "provider": "Sam's"},
        {"name": "Sobrecitos coffe mete", "unit": "pz", "ideal": 1.0, "provider": "Sam's"},
        {"name": "Sobres de Stevia", "unit": "pz", "ideal": 1.0, "provider": "Sam's"},
        {"name": "Nesquik", "unit": "bote", "ideal": 1.5, "provider": "Sam's"},
        {"name": "Nescafe", "unit": "frascos", "ideal": 1.0, "provider": "Sam's"},
        {"name": "Cappuccino vainilla en polvo", "unit": "lata", "ideal": 0.5, "provider": "Sam's"},
        {"name": "Helado vainilla", "unit": "pz", "ideal": 1.0, "provider": "Sam's"},
        {"name": "Helado chocolate", "unit": "pz", "ideal": 1.0, "provider": "Sam's"},
        {"name": "Helado fresa", "unit": "pz", "ideal": 1.0, "provider": "Sam's"},
        {"name": "Mordisko", "unit": "caja", "ideal": 1.0, "provider": "Sam's"},
        {"name": "Paleta Kit Kat", "unit": "Paletas", "ideal": 7.0, "provider": "Sam's"},
        {"name": "Magnum", "unit": "Paletas", "ideal": 11.0, "provider": "Sam's"},
        {"name": "Magnum sam's", "unit": "pz", "ideal": 11.0, "provider": "Sam's"},
        {"name": "Paleta pelon pelo rico", "unit": "paletas", "ideal": 6.0, "provider": "Sam's"},
        {"name": "Paletas de Miguelito", "unit": "pz", "ideal": 1.0, "provider": "Sam's"},
        {"name": "Bolitas de Ferrero Rocher", "unit": "pz", "ideal": 1.0, "provider": "Sam's"},

        # ================= WALMART =================
        {"name": "Baguette", "unit": "pz", "ideal": 3.0, "provider": "Walmart"},
        {"name": "Servitoallas", "unit": "pz", "ideal": 4.0, "provider": "Walmart"},
        {"name": "Latas de jitomate para tapas", "unit": "latas", "ideal": 2.0, "provider": "Walmart"},
        {"name": "Cajitas para pasteles", "unit": "pz", "ideal": 1.0, "provider": "Walmart"},
        {"name": "Chocolate", "unit": "pz", "ideal": 2.0, "provider": "Walmart"},
        {"name": "Vainilla", "unit": "pz", "ideal": 2.0, "provider": "Walmart"},
        {"name": "Red velvet", "unit": "pz", "ideal": 2.0, "provider": "Walmart"},
        {"name": "Pan de vino", "unit": "pz", "ideal": 2.0, "provider": "Walmart"},
        {"name": "Betún de pasteles", "unit": "pz", "ideal": 2.0, "provider": "Walmart"},
        {"name": "Finca las moras tinto", "unit": "botella", "ideal": 3.5, "provider": "Walmart"},
        {"name": "Finca las moras rosado", "unit": "botellas", "ideal": 4.0, "provider": "Walmart"},
        {"name": "Casillero del diablo tinto", "unit": "botellas", "ideal": 3.0, "provider": "Walmart"},
        {"name": "Casillero del diablo rosado", "unit": "botellas", "ideal": 4.0, "provider": "Walmart"},
        {"name": "Lambrusco tinto", "unit": "botella", "ideal": 3.5, "provider": "Walmart"},
        {"name": "Lambrusco rosado", "unit": "botellas", "ideal": 2.0, "provider": "Walmart"},
        {"name": "Antillano", "unit": "botellas", "ideal": 8.0, "provider": "Walmart"},
        {"name": "Leche santa clara deslactosada", "unit": "pz", "ideal": 6.0, "provider": "Walmart"},
        {"name": "Leche santa clara", "unit": "pz", "ideal": 1.0, "provider": "Walmart"},
        {"name": "Mermelada de zarzamora", "unit": "frasco", "ideal": 1.0, "provider": "Walmart"},
        {"name": "Harina integral", "unit": "kg", "ideal": 3.0, "provider": "Walmart"},
        {"name": "Azúcar glass", "unit": "pz", "ideal": 1.0, "provider": "Walmart"},

        # ================= CARNES MARST =================
        {"name": "Aros de cebolla", "unit": "bolsas", "ideal": 7.0, "provider": "Carnes Marst"},
        {"name": "Dedos de queso", "unit": "bolsas", "ideal": 8.0, "provider": "Carnes Marst"},
        {"name": "Bonneles", "unit": "bolsas", "ideal": 7.0, "provider": "Carnes Marst"},
        {"name": "Papas gajo", "unit": "bolsas", "ideal": 7.0, "provider": "Carnes Marst"},
        {"name": "Papas francesas", "unit": "bolsas", "ideal": 4.0, "provider": "Carnes Marst"},
        {"name": "Costillas", "unit": "costillares", "ideal": 3.0, "provider": "Carnes Marst"},
        {"name": "Parmesano", "unit": "bote", "ideal": 1.0, "provider": "Carnes Marst"},
        {"name": "Papa raquet", "unit": "bolsas", "ideal": 4.0, "provider": "Carnes Marst"},
        {"name": "Nuggets", "unit": "bolsas", "ideal": 2.0, "provider": "Carnes Marst"},
        {"name": "Nuggets kids", "unit": "bolsas", "ideal": 2.0, "provider": "Carnes Marst"},
        {"name": "Mozarella", "unit": "barras", "ideal": 8.0, "provider": "Carnes Marst"},
        {"name": "Peperoni", "unit": "pz", "ideal": 2.0, "provider": "Carnes Marst"},
        {"name": "Bote para rellenar catsup", "unit": "pz", "ideal": 1.0, "provider": "Carnes Marst"},
        {"name": "Sangría", "unit": "pz", "ideal": 5.0, "provider": "Carnes Marst"},

        # ================= CENTRAL =================
        {"name": "Servilletas", "unit": "piezas", "ideal": 2.0, "provider": "Central"},
        {"name": "Costal de harina", "unit": "costal", "ideal": 1.0, "provider": "Central"},
        {"name": "Bolsa negra jumbo n 2 kilos", "unit": "kilos", "ideal": 2.0, "provider": "Central"},
        {"name": "Bolsa de craft #06", "unit": "paquetes", "ideal": 1.0, "provider": "Central"},
        {"name": "Charola unicell negra G medio", "unit": "paq chico", "ideal": 1.0, "provider": "Central"},
        {"name": "Charola de unicel negra CH 1 y medio", "unit": "chico", "ideal": 1.5, "provider": "Central"},
        {"name": "Papel de aluminio", "unit": "pz", "ideal": 1.0, "provider": "Central"},
        {"name": "Pulpa de tamarindo", "unit": "pz", "ideal": 5.0, "provider": "Central"},
        {"name": "Levadura", "unit": "pz", "ideal": 2.0, "provider": "Central"},
        {"name": "Chile de árbol", "unit": "bolsa", "ideal": 1.0, "provider": "Central"},
        {"name": "Orégano", "unit": "kilo", "ideal": 0.5, "provider": "Central"},
        {"name": "Botecitos para llevar aderezos", "unit": "paquetes", "ideal": 2.0, "provider": "Central"},
        {"name": "Tapas para llevar aderezos", "unit": "paquetes", "ideal": 6.0, "provider": "Central"},
        {"name": "Vaso para postre cristal", "unit": "paquete", "ideal": 1.0, "provider": "Central"},
        {"name": "Tapa para postre cristal", "unit": "paquete", "ideal": 1.0, "provider": "Central"},
        {"name": "Cucharas para postre", "unit": "paquetes", "ideal": 4.0, "provider": "Central"},
        {"name": "Boing", "unit": "caja completa", "ideal": 1.0, "provider": "Central"},
        {"name": "Leche nutri.", "unit": "pz", "ideal": 13.0, "provider": "Central"},
        {"name": "Huevo", "unit": "tapa", "ideal": 1.0, "provider": "Central"},
        {"name": "Mantequilla iberia", "unit": "pz", "ideal": 1.0, "provider": "Central"},
        {"name": "Costal de azúcar", "unit": "chico", "ideal": 1.0, "provider": "Central"},
        {"name": "Chochitos", "unit": "kilo", "ideal": 0.5, "provider": "Central"},
        {"name": "Coco rallado", "unit": "bolsa", "ideal": 1.0, "provider": "Central"},
        {"name": "Canela en polvo", "unit": "bolsa", "ideal": 1.0, "provider": "Central"},
        {"name": "Vainilla", "unit": "botella", "ideal": 1.0, "provider": "Central"},
        {"name": "Ambiante", "unit": "pzs", "ideal": 2.0, "provider": "Central"},
        {"name": "Bolitas explosivas de cereza", "unit": "bote", "ideal": 1.0, "provider": "Central"},
        {"name": "Mazapán para frappe", "unit": "bolsa", "ideal": 1.0, "provider": "Central"},
        {"name": "Barquillos de chocolate", "unit": "bote", "ideal": 1.0, "provider": "Central"},
        {"name": "Banderillas de tamarindo", "unit": "bote", "ideal": 1.0, "provider": "Central"},
        {"name": "Costal chile en polvo", "unit": "costal", "ideal": 1.0, "provider": "Central"},
        {"name": "Costal Miguelito original", "unit": "costal", "ideal": 0.5, "provider": "Central"},
        {"name": "Popotes", "unit": "caja", "ideal": 1.0, "provider": "Central"},
        {"name": "Vaso litro", "unit": "paquete", "ideal": 1.0, "provider": "Central"},
        {"name": "Tapa vaso litro", "unit": "paquete", "ideal": 1.0, "provider": "Central"},
        {"name": "Vaso medio litro", "unit": "paquete", "ideal": 1.0, "provider": "Central"},
        {"name": "Tapa vaso medio litro", "unit": "paquete", "ideal": 1.0, "provider": "Central"},
        {"name": "Vaso frappe", "unit": "paquete", "ideal": 1.0, "provider": "Central"},
        {"name": "Tapa vaso frappé", "unit": "paquete", "ideal": 1.0, "provider": "Central"},
        {"name": "Vaso para michelada", "unit": "paquete", "ideal": 1.0, "provider": "Central"},

        # ================= VALENCIANA =================
        {"name": "Absolut", "unit": "patona", "ideal": 2.0, "provider": "Valenciana"},
        {"name": "Aperol", "unit": "botellas", "ideal": 1.5, "provider": "Valenciana"},
        {"name": "Bacardi de 700ml", "unit": "botella", "ideal": 1.0, "provider": "Valenciana"},
        {"name": "Bayles", "unit": "botellas", "ideal": 2.0, "provider": "Valenciana"},
        {"name": "Buchanan's 750ml", "unit": "botella", "ideal": 1.0, "provider": "Valenciana"},
        {"name": "Controy", "unit": "botella", "ideal": 0.5, "provider": "Valenciana"},
        {"name": "Curazao azul", "unit": "botella", "ideal": 1.5, "provider": "Valenciana"},
        {"name": "Disaronno", "unit": "botellas", "ideal": 1.5, "provider": "Valenciana"},
        {"name": "Don Julio 70", "unit": "botella", "ideal": 0.5, "provider": "Valenciana"},
        {"name": "Etiqueta Negra (Black Label)", "unit": "botella", "ideal": 1.5, "provider": "Valenciana"},
        {"name": "Etiqueta roja (Red Label)", "unit": "botellas", "ideal": 5.0, "provider": "Valenciana"},
        {"name": "Etiqueta roja patona", "unit": "patona", "ideal": 1.0, "provider": "Valenciana"},
        {"name": "Ginebra", "unit": "patona", "ideal": 1.5, "provider": "Valenciana"},
        {"name": "Ginebra rosado", "unit": "botella", "ideal": 1.0, "provider": "Valenciana"},
        {"name": "Jagermeister", "unit": "patona", "ideal": 1.0, "provider": "Valenciana"},
        {"name": "Jack Daniel's", "unit": "botella", "ideal": 1.5, "provider": "Valenciana"},
        {"name": "Kahlúa", "unit": "botella", "ideal": 1.0, "provider": "Valenciana"},
        {"name": "Licor 43", "unit": "botella", "ideal": 1.0, "provider": "Valenciana"},
        {"name": "Licor de melón", "unit": "botella", "ideal": 1.0, "provider": "Valenciana"},
        {"name": "Malibú", "unit": "botella", "ideal": 1.0, "provider": "Valenciana"},
        {"name": "Mezcal 400 conejos", "unit": "botella", "ideal": 1.5, "provider": "Valenciana"},
        {"name": "Tequila 1800 añejo", "unit": "botella", "ideal": 2.5, "provider": "Valenciana"},
        {"name": "Tequila 1800 blanco", "unit": "botella", "ideal": 1.0, "provider": "Valenciana"},
        {"name": "Tequila José Cuervo Especial", "unit": "botella", "ideal": 1.0, "provider": "Valenciana"},
        {"name": "Tequila José Cuervo Tradicional 695ml", "unit": "botella", "ideal": 1.0, "provider": "Valenciana"},
        {"name": "Patona Tequila Jose cuervo tradicional", "unit": "patonas", "ideal": 2.0, "provider": "Valenciana"},
        {"name": "Tequila Maestro Dobel", "unit": "botellas", "ideal": 2.0, "provider": "Valenciana"},
        {"name": "Torres", "unit": "botella", "ideal": 1.0, "provider": "Valenciana"},
        {"name": "Torres 10 patona", "unit": "patona", "ideal": 1.0, "provider": "Valenciana"}
    ]

    for p_data in products_data:
        new_product = models.Product(
            name=p_data["name"],
            unit_measure=p_data["unit"],
            ideal_stock=p_data["ideal"],
            current_stock=0.0, 
            provider_id=providers[p_data["provider"]].id
        )
        db.add(new_product)
    
    db.commit()
    db.close()
    print("¡Base de datos inyectada con TODO EL CATÁLOGO MAESTRO de Pizzetas Artesanales!")

if __name__ == "__main__":
    seed_database()